config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users, :controllers => {:sessions => 'sessions'}
  resources :users
  resources :posts, except: [:show]

  get 'safenet_labs_repository' => redirect('https://github.com/safenetlabs')

end

app/models/post.rb
# require 'keyziio'
# require 'keyziio_client'
# require 'json'
require 'base64'
require 'securerandom'

class Post < ActiveRecord::Base
  belongs_to :user
  attr_accessor :encrypted_content
  # before_save :encrypt_post
  # after_find :decrypt_post


  before_save :encrypt
  after_find :decrypt

  def encrypt
    # Get keychain key from the memory cache
    keychain_key = KeyziioCache.cache.read(self.user.keychain_id)
    kz_user = KZClient.new(self.user.keychain_id, self.user.access_token, Base64.decode64(keychain_key))
    self.content = kz_user.encrypt_buffer(content, self.title + '_key')
  end

  def decrypt
    self.encrypted_content = content
    # Get the keychain key from the memory cache
    keychain_key = KeyziioCache.cache.read(self.user.keychain_id)
    kz_user = KZClient.new(self.user.keychain_id, self.user.access_token, Base64.decode64(keychain_key))
    begin
      self.content = kz_user.decrypt_buffer(content) if kz_user
    rescue RestClient::InternalServerError
      true
    end
  end

  # def encrypt
  #   kzu = JSON.parse(KeyziioAgent.kza.get_user(self.user.id))
  #   kzuser = KZClient.new
  #   kzuser.inject_user_key(kzu['private_key'], kzu['id'])
  #   self.content = kzuser.encrypt_buffer(content, 'u3_key1')
  # end
  #
  # def decrypt
  #   kzu = JSON.parse(KeyziioAgent.kza.get_user(self.user.id))
  #   kzuser = KZClient.new
  #   kzuser.inject_user_key(kzu['private_key'], kzu['id'])
  #   self.encrypted_content = content
  #   self.content = kzuser.decrypt_buffer(content)
  # end








  # def encrypt_post
  #   # agent = Keyziio::Agent.new('cnZNqHoOXDML9eSSZI')
  #   response = @kza.get_user(current_user)
  #   client = KZClient.new
  #   client.inject_user_key(JSON.parse(response)['private_key'], JSON.parse(response)['id'])
  #   client.encrypt_buffer(:content, 'u3_key1')
  # end
  #
  # def decrypt_post
  #   # agent = Keyziio::Agent.new('cnZNqHoOXDML9eSSZI')
  #   response = @kza.get_user(current_user)
  #   client = KZClient.new
  #   client.inject_user_key(JSON.parse(response)['private_key'], JSON.parse(response)['id'])
  #   begin
  #     client.decrypt_buffer(:content)
  #   rescue KeyziioDecodeException
  #     :content
  #   end
end

app/models/user.rb
require 'json'

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, if: :new_record?
  after_create :create_keyziio_user
  has_many :posts

  def setup_client_session
    if KeyziioCache.cache.read(self.keychain_id) == nil
      # Create a client instance and inject key
      kz_user = KZClient.new(self.keychain_id, self.access_token)
      # get session public key from the keyziio client lib
      session_key = kz_user.get_session_key

      # Get user keychain for the user key part
      keychain_response = KeyziioAgent.kza.get_keychain(self.keychain_id)

      # Send key part back to be rewrapped with user session public
      wrapped_key_part = KeyziioAgent.kza.wrap_key_part(JSON.parse(keychain_response)['keypart'], session_key)

      # Now, inject wrapped key in the client
      keychain_key = kz_user.construct_keychain_key(wrapped_key_part)

      # Cache kz_user object
      KeyziioCache.cache.write(self.keychain_id, keychain_key)
    end
  end

  def init_keyziio_client
    access_token = KeyziioAgent.kza.get_client_token(self.keychain_id)
    self.update_attributes(:access_token => access_token)
    self.setup_client_session
  end

  def create_keyziio_user
    keychain_id = KeyziioAgent.kza.create_keychain(self.id)
    self.update_attributes(:keychain_id => keychain_id)
    self.init_keyziio_client
  end

  def after_database_authentication
    # This is a devise callback, which is initiated after successfully authenticating
    self.init_keyziio_client
  end


  def set_default_role
    self.role ||= :user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_filter :authenticate_user!
  # after_action :verify_authorized, except: [:index]
  # after_action :verify_policy_scoped, only: [:index]

  def index
    @posts = policy_scope(Post.limit(10))
    # @posts.each do |post|
    #   post[:content] = decrypt(current_user.name, post[:encrypted_content])
    # end
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    # @post = Post.new(params[:post])
    # @post.user = current_user
    @post = current_user.posts.build(secure_attributes)

    if @post.save
      redirect_to posts_path, notice: 'Post posted!'
    else
      render :new
    end



    # @post = current_user.posts.build(secure_attributes)
    # authorize @post
    # @post[:encrypted_content] = encrypt(current_user.name, @post.content)
    # if @post.save
    #   redirect_to posts_path, notice: 'Post posted!'
    # else
    #   render :new
    # end
  end

  def edit
    @post = Post.find(params[:id])

    # load_post
    # authorize @post
    # @post[:content] = decrypt(current_user.name, @post[:encrypted_content])
  end

  def new
    @post = Post.new
    # authorize @post
  end

  def update
    @post = Post.find(params[:id])

    # load_post
    # authorize @post
    if @post.update_attributes(secure_attributes)
      redirect_to posts_path, notice: 'Post updated!'
    else
      render :edit
    end
  end

  def destroy
    load_post
    authorize @post
    @post.destroy
    redirect_to posts_path, notice: 'Post unposted!'
  end

  private

    def load_post
      @post = Post.find(params[:id])
    end

    def secure_attributes
      params.require(:post).permit(:title, :content)
    end

    # def decrypt(user, content)
    #   Post.decrypt_post(user, content)
    # end
    #
    # def encrypt(user, content)
    #   Post.encrypt_post(user, content)
    # end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  def destroy
    # Clear keychain key for this user in the keyziio cache
    KeyziioCache.cache.delete(current_user.keychain_id)
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, notice: 'User updated.'
    else
      redirect_to users_path, alert: 'Unable to update user.'
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, notice: 'User deleted.'
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'
      - if user_signed_in?
        p.navbar-text.navbar-right Signed in as #{current_user.email}

app/views/layouts/_navigation_links.html.slim
- # add navigation links to this file
- if user_signed_in?
  li
    = link_to 'Edit account', edit_user_registration_path
  li
    = link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  li
    = link_to 'Sign in', new_user_session_path
  li
    = link_to 'Sign up', new_user_registration_path
- if user_signed_in?
  li = link_to 'Posts', posts_path
  - if current_user.admin?
    li
      = link_to 'Users', users_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Blog'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Blog'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/posts/_form.html.slim
div
  = form_for @post do |f|
    .form-group
      = f.label 'Title'
      = f.text_field :title, autofocus: true, class: 'form-control'
    .form-group
      = f.text_area :content, class: 'form-control', rows: 10
    = f.submit 'Save', class: 'btn btn-primary'

app/views/posts/edit.html.slim
h1 Edit Post

= render 'form'

app/views/posts/index.html.slim
h1 Your Posts
table
  thead
    tr
      th Title
      th Readable
      th Database Copy
      th colspan="2" Actions
  tbody
    - @posts.each do |post|
      tr
        td =post.title
        td =post.content
        td =post.encrypted_content
        td =link_to 'Edit', edit_post_path(post), class: 'btn btn-default'
        td =button_to 'Delete', post_path(post), method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure?'}
= link_to 'New', new_post_path, class: 'btn btn-primary'

app/views/posts/new.html.slim
h1 Create a New Post

= render 'form'

app/views/users/_user.html.slim
td
  = link_to user.email, user
td
  = form_for(user) do |f|
    = f.select(:role, User.roles.keys.map {|role| [role.titleize,role]})
    = f.submit 'Change Role', :class => 'button-xs'
td
  = link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user

app/views/users/index.html.slim
.container
  .row
    h3
      | Users
    .column
      table.table
        tbody
          - @users.each do |user|
            tr
              = render user

app/views/users/show.html.slim
h3
  | User
p
  | Name: 
  = @user.name if @user.name
p
  | Email: 
  = @user.email if @user.email

app/views/visitors/index.html.slim
h3 Keyzi.io demonstration application
p This is a simple blogging application that implements keyzi.io for encryption/decryption
p add the following lines to your gemfile
pre gem 'keyziio', github: "safenetlabs/ruby-keyziio-agent"
    gem 'keyziio_client', github: "safenetlabs/ruby-keyziio-client"
p The posts model only stores the encrypted content - and model callbacks are implemented to encrypt and decrypt content
  In order to configure the application you should add your keyzi.io token to secrets.yml
  and create an instance of the agent that communicates with the keyzi.io server in an initializer - for example keyziio_agent.rb
pre module KeyziioAgent
      @kza = Keyziio::Agent.new(Rails.application.secrets.keyziio_id)
      def self.kza
        @kza
      end
    end

p The user model implements call back :after_create to setup user's keychain on the Keyziio server. On create and each sign in,
  the user's keychain key parts are request from Keyziio Agent running on the ASP's app server and the Keyziio server. The two keyparts are
  joined to construct the user's keychain key and store it in a memory cache. This cached key is used to unwrap data keys during encrypt and decrypt operations.
  The key is stored only for the current session and purged from the cache on sign out.

p In the posts model we implement call backs :before_save and :after_find to handle the encryption and decryption
pre before_save :encrypt
    def encrypt
      keychain_key = KeyziioCache.cache.read(self.user.keychain_id)
      kz_user = KZClient.new(self.user.keychain_id, self.user.access_token, Base64.decode64(keychain_key))
      self.content = kz_user.encrypt_buffer(content, self.title + '_key')
    end
pre after_find :decrypt
    def decrypt
      self.encrypted_content = content
      # Get the keychain key from the memory cache
      keychain_key = KeyziioCache.cache.read(self.user.keychain_id)
      kz_user = KZClient.new(self.user.keychain_id, self.user.access_token, Base64.decode64(keychain_key))
      self.content = kz_user.decrypt_buffer(content) if kz_user
    end
p You can get the two gem files from here
=link_to 'safenet labs repository', safenet_labs_repository_url